### ISSUE TITLE
SpoutCam not working in Mediapipe tox

### ISSUE THREAD

**Issue by yiwen212** [torinmb/mediapipe-touchdesigner#45] opened 2023-10-05 20:36 UTC
Hi Torin and Dom, Thanks for all amazing tool. Making it easy for beginners to get started.
I have some problems while using webcam with SpoutCam. I selected 'webcam' in videofilein TOP, and selected 'SpoutCam' in the Mediapipe tox. Both of the resolutions are set to 1280 x 720. However, the Mediapipe window shows RGB noise.
![螢幕擷取畫面 (45)](https://github.com/torinmb/mediapipe-touchdesigner/assets/147087782/4ff90c10-3a74-4005-af7b-fb1df278eb65)

When I use laptop cam and obs in Mediapipe tox, it is successful. Using the webcam, Mediapipe window have image but not working.
![螢幕擷取畫面 (49)](https://github.com/torinmb/mediapipe-touchdesigner/assets/147087782/2950bda7-0d89-43c1-9ff8-a15563dce996)

 I also tried changing the port to 3002, but not working.
![螢幕擷取畫面 (50)](https://github.com/torinmb/mediapipe-touchdesigner/assets/147087782/ad9006ce-a70a-4499-bae4-9a9842512e70)

I found an interesting part: when I select 'SpoutCam' in Mediapipe tox, window shows RGB noise. However, when I open videofilein TOP and also select 'SpoutCam',  videofilein TOP shows the image.
![螢幕擷取畫面 (46)](https://github.com/torinmb/mediapipe-touchdesigner/assets/147087782/cfb5c9e9-7482-47c1-9b49-33172a81768b)

These are the images that I tried loading http://localhost:9222/.
Select 'webcam' in Mediapipe tox
![螢幕擷取畫面 (51)](https://github.com/torinmb/mediapipe-touchdesigner/assets/147087782/2e5bf3b1-0e58-4fd0-8298-dbf871b739ec)
Select 'SpoutCam' in Mediapipe tox
![螢幕擷取畫面 (52)](https://github.com/torinmb/mediapipe-touchdesigner/assets/147087782/a213382e-5715-4733-ae83-0e7082ff7d07)

TD Version：2022.33910, 2022.35280
MediaPipe TD Release：v0.2.2
System：Windows 11

If there's anything I haven't noticed or done wrong, please let me know! Thank you for your guidance!

**Comment by jossevessies** [comment] 2023-10-06 05:53
Hi Yiwen, have you tried changing the byte size to 8-bit (fixed) rgba?
For me this was a solution.

also I didn’t realize before, but in the mediapipe.toe file that comes with the project Torin and Dom added a spoutout top. Of course disable this feed-out to use your own in the right spout channel name.

**Comment by yiwen212** [comment] 2023-10-06 08:14
Hi jossevessies, I got it. I'll give it a try. Thank you very much!!

**Comment by Truen224** [comment] 2023-10-16 02:00
I have the same issue. Version I'm running is 2022.33910
I attempted to use MovieFileIn TOP to SyphonSpoutOut TOP and then to Mediapipe, but it seems like Mediapipe cannot receive the Spout Cam (although it works with VideoDeviceIn). 

I'm not sure what went wrong...

![螢幕擷取畫面 2023-10-16 095340](https://github.com/torinmb/mediapipe-touchdesigner/assets/94170192/e591bb36-fec7-440c-aa75-168082fb64e7)

Additionally, a big thank you to Torin and Dom for your amazing work and selfless sharing. I've been trying to integrate Mediapipe with for several months  TouchDesigner without success. Your help has been immensely valuable to me!

**Comment by domisjustanumber** [comment] 2023-11-01 12:29
Hi @Truen224 sorry I missed your reply earlier. If you are still having issues, we have a new release that has many fixes and may solve your problem https://github.com/torinmb/mediapipe-touchdesigner/releases/tag/v0.3.1

**Comment by domisjustanumber** [comment] 2023-11-12 19:11
Closing this one for now, please re-open if you have any other issues

**Closed by domisjustanumber** 2023-11-12 19:11 UTC

**Comment by vVattghern** [comment] 2023-12-04 16:40
I was facing a similar issue with Mediapipe only giving me a noisy SpoutCam output. Any changes made in TouchDesigner or by changing plugin versions (for both this plugin and Mediapipe) did not yield any success. **I'm adding a comment here because I was eventually able to fix it and want to note it down, in case anyone else faces the same problem:** 

For diagnosing the issue, I recommend downloading the Spout2 files from the same GitHub profile as the SpoutCam Plugin. This adds some settings and diagnostics options when working with Spout. In my case, my laptop graphics proved to be the problem! When running diagnostics, checking for compatibility and looking at the running spout cam process (all possible through the SpoutPanel and SpoutSettings) it told me that the texture sharing was failing, thus resulting in the noise. After reading through the SpoutSettings and their explanations (not the SpoutCamSettings!), I made sure to put all processes involving spout (so sender & receiver) on the same graphics pipeline (by changing the .exe graphic settings in Windows, this is explained in SpoutSettings), since my laptop has both integrated CPU graphics, as well as a GPU. 

**This actually fixed my issue!** 

So for anyone that has a laptop, multiple GPUs or any other Spout issues in combination with this TouchDesigner plugin, I recommend downloading the rest of the Spout software and tinkering a bit.

**Comment by domisjustanumber** [comment] 2023-12-04 20:24
@Ayeshmantha-Maduranga does this solve your issue at all?

**Comment by domisjustanumber** [comment] 2025-03-17 20:50
I just encountered this issue after a fresh Windows install on my laptop with an integrated GPU and an NVIDIA GPU and found this as the fix. As @vVattghern mentioned, the issue is the Spout output from TD is not running on the same GPU as MediaPipe, hence the noise.

The only fix I found that worked, was to open the `NVIDIA Control Panel > 3D Settings > Manage 3D Settings` and set the `Preferred graphics processor:` to `High-Performance NVIDIA processor`

![Image](https://github.com/user-attachments/assets/2480f723-e9cb-4835-9ed9-e77f7d372fbf)
